getpopper/popper

build-me.sh
popper/init.go

Hi,
I just read the "Popper Convention" paper and wanted to see what is under the hood. Nice work! I plan on using it for my next papers. In the meanwhile, here are some patches.
Regards,
Cristian

Popper init folder

---

build-me.sh
popper/init.go
popper/main.go

Use XDG folders, instead of littering the user's HOME folder.
For the spec see: https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html
For further justification see: https://ploum.net/184-cleaning-user-preferences-keeping-user-data/

Xdg folders

---

popper/_check/check.py

This update changes the sleep time from a constant 20 seconds to a exponentially
increasing sleep time from 1 second upto 5 minutes(300 seconds).
Closes https://github.com/systemslab/popper/issues/174

Check.py: Updates the sleeptime

---

cli/popper/commands/cmd_run.py

This should address issue #232

Print error message when no pipelines configured. Fixes #232

---

cli/popper/commands/cmd_init.py
cli/popper/utils.py
docs/ci/demo

This fixes the problems faced while initializing a paper pipeline. 
Closes #236

Issue-236 - Initialize paper command fixed

---

cli/popper/cli.py
cli/popper/commands/cmd_env.py
cli/popper/commands/cmd_init.py
cli/popper/commands/cmd_metadata.py
cli/popper/commands/cmd_run.py
cli/popper/commands/cmd_version.py
cli/popper/exceptions.py
cli/popper/utils.py
docs/ci/demo

This addresses the issues #223 and #226

Color functionality added for display of dict and list objects

---

cli/popper/commands/cmd_env.py
cli/popper/commands/cmd_run.py

Brings back the colorized changes and bug fix that got overwritten when
the PR for #224 was merged

Brings back colorized functionality to popper run

---

cli/popper/commands/cmd_init.py
cli/popper/exceptions.py
docs/ci/demo

Issue-250 - teardown check on popper init.

---

docs/ci/popperyml.md

Doc: added info on metadata, pipelines and popperized

---

README.md
docs/ci/popperyml.md

closes #275 
* noticed some indentation errors in the docs because of my pr on #266 . Fixed them.

pypi badge added

---

cli/README.md
cli/extras/bash-completion.sh
cli/popper/cli.py
cli/setup.py

A bash auto-completion feature has been added.
closes #255

CLI: bash auto-completion

---

cli/popper/commands/cmd_run.py

Fixed the error that occurred due to no progress bar object passed to the execute method when teardown stage was run after any stage failed which led popper to crash. Now after any stage fails,
popper will gracefully exit out after running teardown, if present.

Fixes #278 Fix cmd_run.py to gracefully exit when a stage fails

---

cli/popper/cli.py

Suggest command names

---

.gitmodules
cli/Dockerfile
cli/bin/popper
cli/popper/utils.py
cli/setup.py

* Created a git [mirror](https://github.com/UjjwalAyyangar/ruamel-yaml) for ruamel.yaml.
* Added ruamel.yaml as a submodule.
* Added support for installing ruamel.yaml from pip.
Addresses issue #282

Replaced pyyaml with ruamel.yaml

---

.travis.yml

Adds tests for manually installed popper

---

docs/ci/popperyml.md
docs/protocol/getting_started.md

Doc : Adds instructions on adding and removing environments and metadata

---

README.md

A new badge for Licence has been added in the [README](https://github.com/systemslab/popper/blob/master/README.md)
Closes #302

License Badge Added

---

cli/popper/utils.py

Fixes the bug in get_project_root() function as explained in #305

fixed: get_project_root() utility function

---

cli/popper/commands/cmd_add.py

Reduces the number of GitHub API requests required to download a pipeline using the popper add command.

Decreasing API requests for popper add

---

cli/popper/commands/cmd_ci.py
docs/ci/demo

add support for circleci in ci subcommand

---

cli/popper/commands/cmd_add.py
cli/popper/commands/cmd_init.py
cli/popper/commands/cmd_search.py
docs/ci/demo
docs/protocol/getting_started.md

* Added a popper search sub-command that queries github and allows users to list available pipelines of an organization. (Addresses #70 )
* Added support for metadata caching (Addresses #258 )

Cli : Popper search sub-command added

---

.gitignore
cli/popper/commands/cmd_env.py
cli/popper/utils.py
cli/setup.py

Revert " add --ls flag to popper env command"

---

cli/popper/commands/cmd_add.py
cli/popper/commands/cmd_info.py
docs/ci/demo

This addresses the issue #259 
I am waiting for the popper add repository command to be finished, after that I will add the tests.

Issue 259 - Add a popper info command for pipelines

---

cli/popper/commands/cmd_workflow.py
docs/ci/demo

This PR makes a few modifications to the workflow subcommand from #323

CLI : Workflow graph generation modified

---

.gitmodules
cli/Dockerfile
cli/bin/popper
cli/popper/archiving.py
cli/popper/commands/cmd_archive.py
cli/popper/commands/cmd_init.py
cli/setup.py
docs/ci/demo

Required metadata keys are added at the time of the popperizied repository creation and read and parsed at the time of publishing the snapshot.

Fixes #316 Handle metadata for archiving feature

---

cli/popper/commands/cmd_add.py
docs/ci/demo

Support for popper add - download pipeline from any branch

---

cli/popper/commands/cmd_ci.py
cli/popper/commands/cmd_run.py
cli/popper/utils.py

Add non-interactive mode for CI systems

---

cli/popper/commands/cmd_search.py
docs/ci/demo

CLI : Adds --rm and --add flags to popper search command

---

.gitignore
cli/popper/commands/cmd_env.py
cli/popper/utils.py
docs/ci/demo

add --list flag to popper env command

---

cli/popper/commands/cmd_ci.py
cli/popper/commands/cmd_run.py
docs/ci/demo

Addresses https://github.com/systemslab/popper/issues/331

cli: add '--skip' flag to 'ci' command to skip execution of certain pipelines

---

docs/sections/examples.md

Addresses the docker example point from #355

Add docker example to docs

---

docs/sections/examples.md

addresses https://github.com/systemslab/popper/issues/355

Adds virtualenv documentation and examples

---

docs/sections/examples.md

Addresses the vagrant example point from #355

Add vagrant example to docs

---

ci/test-env-vars.sh
ci/test-existing.sh
ci/test-init.sh
ci/test-reset.sh
ci/test-search.sh

Fix tests that expect errors

---

ci/test-env-vars.sh
ci/test-env.sh
ci/test-stages.sh
ci/test-workflow.sh
cli/popper/commands/cmd_env-vars.py
cli/popper/commands/cmd_env.py
cli/popper/commands/cmd_stages.py
cli/popper/commands/cmd_workflow.py
cli/popper/utils.py

Fixes issues 379

---

cli/popper/commands/cmd_run.py

Update popper whitelist

---

ci/test-run.sh
cli/popper/commands/cmd_run.py

cli: extend popper run --skip argument to allow skipping specific stages

---

ci/test-reset.sh
cli/popper/commands/cmd_reset.py
cli/popper/utils.py

Addresses #392 
Fixes the bug in `make_gh_request` function in `utils.py`

Confirmation prompt added to reset subcommand

---

cli/popper/commands/cmd_rm.py
cli/setup.py

* Addresses #398 
* Modifies lark-parser version is setup.py

Fixes the behaviour of `popper rm` subcommand

---

ci/test-badge.sh
cli/popper/commands/cmd_badge.py

This command will generate markdown for getting a popper badge.

Fixes #139 Add service popper to the popper badge command

---

ci/test-badge.sh
cli/popper/commands/cmd_badge.py

This command lists all the records of all status updates stored for a project

Fixes #180 Add a badge --history command

---

ci/test-init.sh
cli/popper/commands/cmd_init.py

Adds support for initializing a pipeline in any folder

---

ci/test-mv.sh
cli/popper/commands/cmd_init.py
cli/popper/commands/cmd_mv.py

CLI : Popper mv command

---

.popper.yml
ci/test-ci.sh
ci/test-require.sh
cli/popper/commands/cmd_ci.py
cli/popper/commands/cmd_require.py
cli/popper/commands/cmd_run.py
cli/popper/utils.py

Adds ability to declare required environment variables

---

ci/test-run.sh
cli/popper/commands/cmd_init.py
cli/popper/commands/cmd_run.py

Add correct entries to '.gitignore'

---

cli/popper/commands/cmd_badge.py
cli/popper/commands/cmd_run.py

The code for the server has been modified.

Fixes #418 Notify the server about the branch

---

cli/popper/commands/cmd_run.py

Addresses https://github.com/systemslab/popper/issues/437

Popper run fails on unsuccessful stage

---

.popper.yml
ci/test-ls.sh
cli/popper/commands/cmd_ls.py

popper ls command added

---

ci/test-ci.sh
cli/popper/commands/cmd_ci.py

Add gitlab support to popper ci command

---

ci/common-setup.sh
ci/test-run.sh
cli/popper/commands/cmd_run.py

Addresses #442. This also includes a refactor of the `test-run.sh` test script.

Fix regression for skipping whole pipelines

---

cli/popper/commands/cmd_ci.py

Change docker image in .gitlab-ci.yml

---

docs/sections/cli_features.md

Addresses the corresponding section of #393.
[skip ci]

Add search and import section to docs

---

ci/test-run.sh
cli/popper/commands/cmd_run.py

Use correct exit code in 'popper run'

---

ci/test-init.sh
cli/popper/commands/cmd_init.py
cli/popper/commands/cmd_run.py
cli/popper/utils.py
docs/sections/cli_features.md

Allow disabling the popper run timeout and setting per pipeline timeouts

---

docs/index.rst
docs/sections/ci_features.md

describe how matrix execution works

new CI section

---

.popper.yml
ci/popper/host/setup.sh.err
ci/test-defaults.sh
ci/test-env.sh
ci/test-existing.sh
ci/test-init.sh
ci/test-matrix-execution.sh
cli/popper/commands/cmd_env.py
cli/popper/commands/cmd_init.py
cli/popper/commands/cmd_run.py
cli/popper/utils.py

addresses https://github.com/systemslab/popper/issues/454

Add args to Docker env

---

.popper.yml
ci/test-reset.sh
ci/test-version.sh
cli/popper/commands/cmd_init.py
cli/popper/commands/cmd_reset.py
cli/popper/template.py
cli/popper/utils.py

Addresses :
* #432
*  #433 
*  #458 (reset subcommand for resetting a popper repository)
* #243 
The current sample can be seen [here](https://github.com/UjjwalAyyangar/MockPipeline/tree/master/pipelines/dummy_pipeline)

CLI : Auto generates readme templates for popper

---

_layouts/default.html

Signed-off-by: Michael A. Sevilla <mikesevilla3@gmail.com>

fix: link overview to existing page

---

.gitignore

Added `cli/build` & `cli/dist` to `.gitignore`

Fixes #517 Fixed .gitignore file

---

.gitmodules
.travis.yml
cli/bin/popper
cli/popper/gha.py
cli/setup.py

fix python 2 to 3 compatibility

---

ci/test/recursive
cli/popper/commands/cmd_run.py

Added --recursive for issue #499. @ivotron please review it

Written fix for issue #499 

---

ci/cli.workflow
ci/test/verbose
cli/popper/commands/cmd_run.py
cli/popper/gha.py
cli/popper/utils.py

When `popper run --verbose` is run, the ouput of all the commands invoked get printed to the output.

Fixes #502 Added --verbose flag

---

ci/cli.workflow
ci/test/scaffold
cli/popper/commands/cmd_scaffold.py
cli/popper/utils.py

Adds command `popper scaffold`.

Implements popper scaffold

---

ci/cli.workflow
ci/test/clone
cli/popper/gha.py
cli/popper/scm.py

Extends uses command to use other git services

---

ci/cli.workflow
ci/test/recursive

Fix missing action recursive in cli.workflow

---

ci/cli.workflow
ci/test/dry-run
cli/popper/commands/cmd_run.py
cli/popper/gha.py
cli/popper/utils.py

Does a dry run of a workflow
Resolves issue #509

Add popper run --dry-run

---

ci/cli.workflow
ci/test/dot
cli/popper/commands/cmd_dot.py
cli/popper/commands/cmd_run.py
cli/popper/commands/cmd_view.py
cli/popper/gha.py
cli/popper/utils.py

Resolve issure #513. `popper view`  now displays ascii-art diag for a workflow.
Example: This [workflow](https://github.com/cplee/github-actions-demo/blob/master/.github/main.workflow) is represented as 
```Ascii for test-and-deploy workflow
+---------------+
|    deploy     |
+---------------+
|
|
v
+------+     +---------------+
| test | <-- | branch_filter |
+------+     +---------------+
|            |
|            |
|            v
|          +---------------+
|          |     lint      |
|          +---------------+
|            |
|            |
|            v
|          +---------------+
+--------> |    install    |
+---------------+
```

Add command - popper dot

---

.gitmodules
.travis.yml
ci/cli.workflow
ci/test/singularity
cli/bin/popper
cli/popper/gha.py
cli/setup.py

Adds a `SingularityRunner` class in `gha.py` to run singularity based action.

Fixes #508 Adds singularity runner

---

.travis.yml

Fixes unpredictable singularity install failures

Fixes #568 Fixes singularity install failures

---

cli/popper/utils.py

Fixes the return code returning mechanism of `utils.exec_cmd`.

Fixes#571 Adds returncode for CalledProcessError

---

cli/popper/gha.py
cli/popper/scm.py

Change fail message

---

ci/test/interrupt
ci/test/parallel
cli/popper/cli.py
cli/popper/commands/cmd_run.py
cli/popper/gha.py
cli/popper/utils.py

Fixes `popper run --parallel` for `HostRunner` .

Fixes#588 popper --parallel for HostRunner

---

cli/popper/commands/cmd_ci.py

Fixes popper install commands in `popper ci`

Fixes#583 Fixed popper install commands

---

ci/cli.workflow
ci/test/common
ci/test/dry-run
ci/test/interrupt
ci/test/quiet
ci/test/singularity
cli/popper/cli.py
cli/popper/gha.py
cli/popper/utils.py

Adds `--debug`,  `--dry-run`  and logging functionality to SingularityRunner

Fixes #576 Added flags to Singularity Runner 

---

ci/test/validate
cli/popper/gha.py

Addresses #612 and #608 and simplifies logic.

Adds more workflow validation rules

---

ci/test/dry-run
ci/test/interrupt
ci/test/quiet
ci/test/singularity
cli/popper/gha.py
docs/sections/extensions.md

The correct format of recipefile for Singularity 2.6+ is a `Singularity` file in actions dir.

Fixes to Singularity Runner

---

ci/test/ci
cli/popper/commands/cmd_ci.py

Adds singularity install support to ci

---

cli/popper/scm.py

Fix scm.clone()

---

cli/popper/gha.py
cli/popper/utils.py

Addresses #602. This feature has been tested locally.

Added error handling for missing software dependencies

---

ci/cli.workflow
ci/test/dot
ci/test/skip
cli/popper/cli.py
cli/popper/commands/cmd_dot.py
cli/popper/commands/cmd_run.py
cli/popper/gha.py
cli/popper/parser.py

Adds --skip flag

---

cli/popper/gha.py

set proper values for GITHUB_EVENT_PATH and HOME inside container.

---

cli/popper/gha.py

Adds workaround for issue-670

---

README.md
ci/test/add
cli/popper/commands/cmd_add.py
cli/popper/gha.py
cli/popper/scm.py

Changes the way 'popper add' copies files

---

ci/test/ci
cli/popper/commands/cmd_ci.py

Add brigade support for ci

---

ci/test/actions-demo
cli/popper/cli.py
cli/popper/commands/cmd_run.py
cli/popper/gha.py
cli/popper/parser.py

Implement --on-failure flag

---

ci/cli.workflow
ci/test/offline
cli/popper/commands/cmd_run.py
cli/popper/gha.py
cli/popper/scm.py

Add --skip-clone and --skip-pull flag

---

ci/test/search
cli/popper/commands/cmd_info.py
cli/popper/commands/cmd_search.py
cli/popper/utils.py

BugFixes and preparing search for release

---

ci/cli.workflow
ci/test/ci
cli/popper/commands/cmd_ci.py

Updated ci to install required runtimes

---

.travis.yml
README.md
cli/popper/utils.py
cli/setup.py
cli/test/test_utils.py

Add unit tests for `utils.py` module.

Adds unit tests for utils.py module

---

ci/test/actions-demo
ci/test/offline
ci/test/parallel
ci/test/reuse
cli/popper/commands/cmd_dot.py
cli/popper/commands/cmd_run.py
cli/popper/gha.py
cli/popper/parser.py
cli/popper/utils.py
cli/test/test_parser.py
cli/test/test_utils.py

#722 and unit test for `parser.py` and lots of refactoring

Add test for parser module and refactoring

---

cli/popper/gha.py

Fix the working dir bug in singularity runtime #717

---

ci/test/actions-demo
cli/popper/gha.py

Fixes #731

---

ci/test/offline
ci/test/reuse
ci/test/search
cli/popper/gha.py
cli/popper/parser.py
cli/popper/utils.py
cli/test/test_gha.py
cli/test/test_utils.py

Adds concurrent execution feature

---

ci/test/dot

`ci/test/dot` test was failing as the example-aws repo being used by it was deleted. So we are now using cplee/github-actions-demo instead.

Fixed dot test

---

cli/popper/scm.py

Resolution for issue https://github.com/systemslab/popper/issues/738

allow popper to run workflows from submodules. issue#728

---

cli/popper/cli.py
cli/popper/commands/cmd_ci.py
cli/popper/commands/cmd_dot.py
cli/popper/commands/cmd_info.py
cli/popper/commands/cmd_run.py
cli/popper/commands/cmd_scaffold.py
cli/popper/commands/cmd_search.py
cli/popper/commands/cmd_version.py
cli/popper/gha.py
cli/popper/log.py
cli/popper/parser.py
cli/popper/scm.py
cli/popper/utils.py

Added the docstrings for the classes and functions.
This is the pr for the issue #700.

Added docstrings to classes and functions

---

.travis.yml
ci/test/actions-demo
cli/popper/scm.py
docs/sections/gha_workflows.md

Support for OAUTH Token for private repos

---

cli/test/test_scaffold.py

The popper scaffold test has been updated using click unit testing.

Adds 'popper scaffold' test 

---

.travis.yml
ci/scripts/install_scripts.sh
ci/test/engine-conf
ci/test/offline
cli/popper/parser.py
cli/popper/runner.py
cli/popper/runner_host.py
cli/popper/runner_slurm.py
cli/test/test_runner_host.py
cli/test/test_runner_slurm.py

Adds singularity runner for host and slurm

Singularity runner

---

README.md

Minor Tweak to ReadMe

---

cli/popper/parser.py
cli/test/test_parser.py

- Adds the error message when the workflow file is empty
- Adds the test

Error message for empty workflow file (#809)

---

src/popper/commands/cmd_help.py
src/test/test_cmd_help.py

add "help" command

---

src/popper/config.py
src/popper/runner.py
src/test/test_runner.py

add `GIT_REMOTE_ORIGIN_URL` to runner.py and update test case

---

examples/ci/bazel.yml

Adds an example workflow in `examples/ci/` of a ci pipeline for bazel projects #863

Add Bazel example workflow

---

install.sh

- Add -e flag to echo so \n is interpreted
- Quote $PWD so that directories with spaces work

Cosmetic fixes to install.sh

---

src/popper/commands/cmd_run.py
src/popper/runner.py
src/popper/runner_host.py
src/popper/runner_slurm.py
src/test/test_runner.py
src/test/test_runner_host.py
src/test/test_runner_slurm.py

This is to make room for the upcoming PodmanRunner.

refactor: Moved repeated functions into StepRunner

---

src/popper/runner_slurm.py
src/test/test_runner_slurm.py

Support for Slurm Runner with Podman

Podman slurm

---

.popper.yml

Skip release pipeline if not on master

Fix CI filtering criteria for builds

---

docs/sections/guides.md

Draft of the computational research guide for R  and RStudio. Finally 🙂
@ivotron

Guide for using Popper with R and RStudio

---

.travis.yml
src/scripts/install_podman.sh

Fix the installation of podman so that tests use the latest stable version rather than the development one.

tests: fix for podman runner

---

src/popper/runner_kubernetes.py

We added the wid to the generated tar file's name and used the cache_dir wherever possible.

Fix #926: Create the workflow context tar in the popper cache dir

---

src/popper/runner_host.py
src/popper/runner_slurm.py
src/test/test_runner_slurm.py

The build appears to fail on Travis, as seen here:
[Travis job](https://travis-ci.com/github/maruthgoyal/popper/jobs/451104742)
In particular, the `sbatch` executable appears to be missing.

Executable checks for SlurmRunner, DockerRunner, SingularityRunner etc as in #812

---

src/popper/runner_host.py

Fixes #815. @ivotron your feedback would be appreciated

Fix --quiet

---

src/popper/commands/cmd_ci.py
src/popper/exporter.py
src/test/test_exporter.py

- adds support for gitlab-ci and matrix builds

cli: exporter support gitlab-ci (#949)

---

examples/gradle/build.gradle
examples/gradle/ci.yml
examples/gradle/src/main/java/StringApp.java
examples/gradle/src/main/java/StringManipulator.java
examples/gradle/src/test/java/StringTester.java

Added a java example that uses gradle as the build system.

example: add a CI pipeline for gradle (#862)

---

.github/workflows/ci.yml
docs/sections/cli_features.md
src/popper/commands/cmd_translate.py
src/popper/translators/translator.py
src/popper/translators/translator_task.py
src/scripts/install_task.sh
src/test/integration/test_translator_task.sh
src/test/test_translator_task.py

This PR releases the Popper-to-Task translator.
See the updated docs for its usage.

Popper-to-Task Translation
