- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
This PR is based on content provided as part of our involvement in the Mozilla's Open Leaders program and includes the following files:
- An updated README.md file
- CONTRIBUTING.md
- CODE_OF_CONDUCT.md
Most of these files were created using [Mozilla's templates](https://github.com/acabunoc/mozfest-repo-template) for the Open Leaders program and are still pretty barebones, so I'm open to any feedback regarding how to improve them.
This should also resolve systemslab/popper#164.
> Add contribution documents and guidelines

- index.md
This commit removes the Popper GIF on the project website and replaces it with a terminal recording of the quickstart guide.
This also closes systemslab/popper#124
> Add asciinema recording of quick start guide

- index.md
I updated the screencast for http://falsifiable.us per this comment by @ivotron : https://github.com/systemslab/popper/issues/124#issuecomment-348935239
If everything looks good, the screencast should be updated as soon as this is merged.
> screencast: fix recording to be compatible with v0.5

- cli/popper/cli.py
A command `Command 'xyz' doesn't exist. Type 'popper --help' for more.`
for an undefined command 'xyz' has been added.
> #231 - Improved the message for undefined commands

- cli/popper/__init__.py
- cli/popper/cli.py
- cli/popper/commands/cmd_version.py
- cli/setup.py
Currently, there are two sources of the version of the popper CLI, namely the setup.py file and the cmd_version.py. In order to avoid having them be out of sync, they have been single-sourced.
Closes #221
> #221-Single-source version of codebase

- cli/popper/utils.py
The read_config() function in utils.py is modified to check if the
.popper.yml file is not empty and if the "metadata" and "pipelines"
dictionaries are defined in it and fail with a proper message if
either criterion is not met.
> Fixes #235 Add check for .popper.yml integrity

- cli/popper/commands/cmd_run.py
- cli/popper/utils.py
- docs/ci/demo
Support for human-friendly timeout values in string format has been added. A function has been added in utils.py which parses the timeout value which can be given as 20s or 10m etc. --timeout option now
takes integer or string as a string and it is converted to seconds accordingly.
> Fixes #228 Add support for providing string timeout values

- cli/popper/commands/cmd_run.py
- cli/popper/utils.py
A --ignore-errors flag has been added to the popper run command which executes all pipelines even when there is an error in one (when no pipeline argument is provided) and shows a warning when used while providing a pipeline argument.
> Fixes #225 Add --ignore-errors flag to 'popper run'

- cli/popper/commands/cmd_run.py
When the popper run command was executed on a pipeline with an invalid stage, python stack traceback was shown for the error where because the code looked for something like validate.err file whereas the file generated is validate.sh.err. This change fixes the error.
> Fixes #239 Correct stage to stage_file in cmd_run.py

- cli/popper/commands/cmd_init.py
- cli/popper/commands/cmd_stages.py
- cli/popper/utils.py
Adds a popper stages command that displays the stages defined in the
.popper.yml file.Also adds a --set flag which redefines the stages of an
existing pipeline.
Fixes https://github.com/systemslab/popper/issues/229
> Adds cmd_stages.py file

- docs/tutorial/from_scratch.md
I found some broken links while reading the live version (on [readthedocs](http://popper.readthedocs.io/)), and I'm pretty sure I caught and corrected the errors on this page.
> fix broken links

- cli/popper/commands/cmd_run.py
- cli/popper/utils.py
- A get_filename method has been added to utils.py for getting the filename of a stage.
- When a stage fails, teardown.sh runs if present and if not skipped.
> Fixes #227 Implement convention of always running 'teardown.sh'

- docs/protocol/getting_started.md
Addresses #267 
* Removed instructions for popper check since it has not been added yet to the python version
* Added instructions on how to run a popper pipeline.
> Doc: popper check removed from getting started guide.

- cli/bin/popper
pyyaml has two separate libs for python2 and python3 and we need
to specifically load the particular lib for popper to work
correctly with both python2 and python3.
First step towards #271.
> Check python version to load pyyaml appropriately

- cli/popper/utils.py
An error had crept up in PR #244 because orange color used for warnings is no ANSI color and hence the warn utility method won't function correctly. Changing 'orange' to 'magenta' does the job.
> Change color of warning from orange to magenta

- .gitmodules
- cli/popper/commands/cmd_add.py
- cli/setup.py
- docs/ci/demo
A new sub-command add is added which adds a pipeline to the repo from existing popperized repositories on github and also updates the .popper.yml as required.
> Fixes #248 Implement a popper add sub-command

- cli/popper/commands/cmd_init.py
- docs/ci/demo
* `--infer-stages` flag added for the `popper init --existing` command
* tests for the new feature added
Closes #254
> Issue-254 : infer-stages flag added to pipeline init

- cli/popper/commands/cmd_cleanup.py
- docs/ci/demo
When a pipeline folder is deleted, its definition stays in the .popper.yml file. This sub-command will ensure that the pipelines folder and the .popper.yml are in sync.
> Fixes #256 Add a popper cleanup sub-command

- README.md
- docs/protocol/getting_started.md
- `popper help` doesn't work, I guess it should be `popper --help` instead
- fix link to carpentry-style lesson
> [Docs] Fix help command in "getting started" and link to software carpentry lesson

- cli/popper/commands/cmd_info.py
- cli/popper/commands/cmd_init.py
This PR :- 
* Changes the api endpoint for the info-subcommand (to make the response faster due to less download)
* Adds a `bad pipeline name` error message for the incorrect usage of the subcommand.
* Fixes the extension of README during the creation of a new pipeline.
> CLI : Changes api endpoint for the info subcommand

- cli/popper/archiving.py
- cli/popper/utils.py
- docs/ci/demo
When popper archive is run on new repository which has not been archived yet, a new record is created otherwise, a new version of a previously existing record is created. Also enabled test for popper archive with zenodo and fixed the tests.
> Fixes #342 Create new record for separate repository

- docs/sections/cli_features.md
Updates the cli features section to use `popper run` instead of `popper check`.
[skip ci]
> Update docs to use popper run

- cli/popper/commands/cmd_run.py
The changes from #443 accidentally made it possible for pipeline stages to be executed out of order. This fixes that.
> Guarantee stage order when skipping

- cli/setup.py
A `,` was missing beside `pyhcl` in `cli/setup.py` file leading to install and build failures which is fixed through this PR.
> Fixes #518 Typo fixes in setup.py

- cli/popper/gha.py
There was a bug in the PR #529 where if a `resolves` or a `uses` attribute was found , it returned which lead to the function not validating the rest of the block and hence errors were thrown afterwards in `normalize` and `check_secrets`. #529  got merged before i could update the PR, hence this new PR.
> Fixes bug in validate_syntax

- ci/test/dry-run
Address Issue #556 
Hi @ivotron, so I was actually checking the dry-run test. So I found that `dry-run` gave different outputs according to different scenarios. So I integrated those in the test.
Scenario 1: Which was occurring most frequently. It is also appeared as a build fail when I rebased #530 [here](https://travis-ci.org/systemslab/popper/jobs/510243060#L294-L303). It happens when the `HostRunner` is called instead of `DockerRunner` class.
(https://travis-ci.org/systemslab/popper/jobs/510243060#L294-L303) https://github.com/systemslab/popper/blob/f4eb8078c23b497faba6de9746984ad526f1861b/ci/test/dry-run#L49-L59
Scenario 2: It happened only once on my local. Thereafter I couldn't reproduce it, but I included it for good measure …
> Add some dry-run test fixes

- ci/test/dry-run
- cli/popper/gha.py
Now , the actions from github, gitlab etc. get cloned to `/tmp/actions/github.com/org/repo/`, `/tmp/actions/gitlab.com/org/repo/` etc. Hence a local clone of any repo gets correctly identified.
> Fixes #533 Modifies the cloned actions path

- ci/cli.workflow
- ci/test/interrupt
- cli/popper/cli.py
- cli/popper/commands/cmd_dot.py
- cli/popper/commands/cmd_run.py
- cli/popper/gha.py
- cli/popper/utils.py
Issue #505: Cleanup docker containers created during `popper run`
Output generated on running `popper run` on this [workflow](https://github.com/cplee/github-actions-demo/blob/master/.github/main.workflow)
```
Already on 'master'
[install] docker pull node:11.6.0
[install] docker create node:11.6.0 npm install
[install] docker start ..
[test] docker pull node:11.6.0
[test] docker create node:11.6.0 npm test
[test] docker start .
[lint] docker build -t action/jshint /root/github-actions-demo/./.github/actions/jshint
[lint] docker create action/jshint 
[lint] docker start .
[branch-filter] docker build -t actions/bin /tmp/actions/actions/bin/./filter
[branch-filter] docker create actions/bin branch master
[branch-filter] docker start .
[deploy] docker build -t actions/bin …
```
> Cleanup on Ctrl+C Signal

- cli/popper/commands/cmd_ci.py
Now, in the CI config files popper is installed through pip by doing `pip install popper/cli` after cloning the repository.
> Fixes #583 Updates the CI config to install popper via pip

- ci/cli.workflow
- ci/test/add
- cli/popper/commands/cmd_add.py
- cli/popper/gha.py
- cli/popper/scm.py
- cli/popper/utils.py
Implements the `popper add` command. On doing `popper add cplee/github-actions-demo` , the repository is cloned, the `main.workflow` file searched, scanned, copied to `project_root` and then the toplevel folder of local actions are also copied which are identified by parsing the workflow.
> Fixes #564 Implements popper add

- ci/test/add
@ivotron  Somehow some redundant tests crept into `ci/test/add`. Fixing that in this PR. Sorry for not noticing it before.
> Fixes add test

- ci/test/dot
- cli/popper/cli.py
- cli/popper/commands/cmd_add.py
- cli/popper/commands/cmd_ci.py
- cli/popper/commands/cmd_dot.py
- cli/popper/commands/cmd_init.py
- cli/popper/commands/cmd_run.py
- cli/popper/commands/cmd_scaffold.py
- cli/popper/commands/cmd_version.py
- cli/popper/gha.py
- cli/popper/scm.py
- cli/popper/utils.py
No more prompts for `secrets` during `popper dot`.
> Fixed popper dot command

- ci/test/singularity
- ci/test/validate
- cli/popper/commands/cmd_add.py
- cli/popper/commands/cmd_dot.py
- cli/popper/commands/cmd_run.py
- cli/popper/gha.py
- cli/popper/parser.py
> Refactored validation functionality and added rules

- ci/cli.workflow
- ci/test/sh
- cli/popper/gha.py
- docs/sections/extensions.md
> Adds sh action

- cli/popper/parser.py
> Improved message for syntax check

- ci/test/actions-demo
- cli/popper/commands/cmd_run.py
- cli/popper/gha.py
- cli/popper/parser.py
> Adds --with-dependencies flag

- .travis.yml
- ci/test/actions-demo
- ci/test/ci
- ci/test/common
- ci/test/dry-run
- ci/test/recursive
- ci/test/skip
- ci/test/validate
- cli/popper/commands/cmd_ci.py
- cli/popper/commands/cmd_run.py
- cli/popper/scm.py
> Makes popper independent of .git

- ci/test/actions-demo
- cli/popper/gha.py
- cli/popper/scm.py
> Rewrite scm.parse() with re

- cli/popper/gha.py
This fixes the case where GitHub Action names have, for example, parentheses in them.
> Replace most invalid docker name characters with underscores

- ci/test/ci
- ci/test/common
- ci/test/dot
- ci/test/samples
- cli/popper/commands/cmd_dot.py
- cli/popper/commands/cmd_run.py
- cli/popper/gha.py
- cli/popper/utils.py
> Allow flags for commit message driven execution

- .travis.yml
- cli/popper/gha.py
- cli/popper/scm.py
- cli/test/test_scm.py
Unit test for `scm.py` module and other fixes.
> Add unit tests and bug fixes for scm.py

- ci/test/offline
- ci/test/reuse
- cli/popper/gha.py
- cli/popper/parser.py
- cli/popper/utils.py
- cli/test/test_gha.py
- cli/test/test_utils.py
> Adds tests for gha.py

- ci/test/actions-demo
- ci/test/parallel
- ci/test/sh
- cli/popper/cli.py
- cli/popper/gha.py
- cli/test/test_gha.py
> Fixes #707 Adds support for exit code 78

- .travis.yml
- cli/test/test_scm.py
Fixes for the unit tests that were failing due to support for OAUTH GitHub token to reference private repositories in action.
> Fixes for the unit test failing

- cli/popper/commands/cmd_ci.py
- cli/popper/commands/cmd_dot.py
- cli/popper/commands/cmd_version.py
- cli/popper/log.py
- cli/popper/runner.py
- cli/popper/scm.py
- cli/popper/utils.py
The refactoring took a lot of the format method away from the repo. I fixed the remaining format usage. We're now covered with Python >3.6x syntax.
> fix f string in codebase #764

- install.sh
Fix #856 
Tested in Centos, Ubuntu and Mac
> map env vars into the popper container from current shell

- docs/sections/cli_features.md
- docs/sections/cn_workflows.md
Update "Customizing container engine behavior" section in the `docs/sections/cli_features.md` file with instructions to use a YAML file instead of a python dictionary
> Update docs for custom container configuration

- docs/sections/cli_features.md
- docs/sections/cn_workflows.md
- src/popper/parser.py
- src/popper/runner_host.py
- src/test/test_parser.py
- src/test/test_runner_host.py
This contains changes allowing to pass step-specific container options to the Docker runner.
Edited some tests to reflect new behavior.
> Implementation of Docker container options for steps

- examples/cd/ansible.yml
- examples/ci/go.yml
This fix is as regards the issue opened at #890
> fix: corrected syntax of example workflows

- install.sh
The call to `docker` must receive the command-line arguments verbatim,
including quotes. Therefore `$@` needs to be quoted.
Without quotes (before):
`popper run -f wf.yml "first step"`
would execute:
`docker run <...> getpopper/popper:v2.7.0 run -f wf.yml first step`
With quotes (after fix):
`docker run <...>  getpopper/popper:v2.7.0 run -f wf.yml "first step"`
> Allow spaces in step IDs

- install.sh
- src/popper/runner_host.py
It says it in the `README.md` that Singularity is not supported by
Popper installed through `install.sh`, but not every user has read it.
This fixes part of #898.
> Add error message that Singularity needs PIP

- install.sh
Fixes GitHub issue #900.
We override the environment variables PATH of the host system with the
default of Popper’s Docker image. This prevents unforeseeable side
effects if the host’s PATH is non-standard.
I obtained the default PATH from the Popper image like this:
```
docker run --rm --entrypoint sh getpopper/popper -c printenv | grep PATH
```
> Override the host’s PATH with Alpine’s default

- src/popper/runner.py
- src/popper/runner_host.py
- src/popper/scm.py
- src/test/test_scm.py
Small tweak on how empty Git repos are identified. Uses `git rev-list -n 1 -all` to check if there are commits in the currently checked out branch.
> cli: modify way in which empty git repos are identified

- docs/sections/cn_workflows.md
- src/popper/runner_kubernetes.py
Allows users to use options to specify non-default path and volume size in the config file. Added these new options to the documentation (cn_workflows.md).
> Issue #928: Suggesting a fix for non-default hostPath volumes

- src/popper/runner_kubernetes.py
Based off of what the description of the issue said and the generous aid from slack this is my current idea for the solution to this problem. I
Seeing as the base premise involved re-ordering the list of nodes I assumed the order was of little consequence aside from having masters last so the non-master nodes will be ordered differently than before.  Furthermore, I considered having two arrays that just got connected after iterating through the nodes but I was unsure if you guys would want to just keep it one array the whole time for cleanliness.
If I have done anything incorrectly or there are issues of cleanliness or efficiency just let me know.
> Fix #927: Prevent trying to schedule on master nodes first

- src/popper/runner_host.py
Resolves #892. @ivotron your feedback would be appreciated.
> Added output for docker pull

- src/setup.py
As stated in [the document](https://docs.python.org/3/distutils/setupscript.html#listing-whole-packages), `popper.translators` must be listed in `packages` in `setup.py` to correctly link packages during the installation.
closes #977
> List `translators` package in `setup.py`

- src/popper/translators/translator_drone.py
- src/test/test_translator_drone.py
This PR adds support for environment variable options in Popper-to-Drone translator. 
Popper has the `env` option to set environment variables in the workflow. You can place `env` under `steps` to define variables for a step, or you can place `env` under `options` to define variables throughout the steps.
Drone has a similar feature `environment` and has almost identical syntax for defining environment variables. However, [it only supports per-pipeline variables](https://docs.drone.io/pipeline/environment/syntax/#:~:text=variables-,Per%20Pipeline,Drone,-supports) (equivalent of `options.env`) in Docker pipelines.
Hence, I made a decision to inject global variables in each step.
Popper injects multiple variables that represent the status of the git repository. The translator automatically …
> support `env` options in translator_drone

- src/popper/commands/cmd_translate.py
- src/popper/translators/translator_drone.py
- src/test/test_translator_drone.py
Close #981 
This PR adds support for `uses: sh` in Popper-to-Drone translator.
Drone's pipelines must be executed by one runner, so Popper workflows need to have the same `type` for its all steps.
For example,
```yml
steps:
- uses: docker://alpine
runs: ["echo", "command 1"]
- uses: docker://alpine
runs: ["echo", "command 2"]
```
this Popper workflow will be translated to `pipeline: docker`.
```yml
steps:
- uses: sh
runs: ["echo", "command 1"]
- uses: sh
runs: ["echo", "command 2"]
```
this will be translated to `pipeline: exec` workflow.
However, 
```yml
steps:
- uses: docker://alpine
runs: ["echo", "command 1"]
- uses: sh
runs: ["echo", "command 2"]
```
this cannot be translated and shows an error.
> Translate `uses: sh` workflows into Drone's Exec Pipeline

- src/popper/translators/translator_drone.py
- src/test/test_translator_drone.py
This PR adds support for `dir` option for Popper-to-Drone translator and makes it possible to run commands in directories other than the root of the repository.
Now the translator is capable of translating [all examples in under `/examples`](https://github.com/getpopper/popper/tree/d7f79f18ed2245b3dd61b7092ca61e4fcfeef9ca/examples) 🎉 
Popper's `dir` corresponds to [`--workdir` on Docker](https://docs.docker.com/engine/reference/run/#workdir) under the hood. However, Drone's runner doesn't support running commands other than the project root.
In this PR, the translator inserts a `cd` command before running the commands to change the working directory.
`dir` options are usually given in absolute path.
https://github.com/getpopper/popper/blob/d7f79f18ed2245b3dd61b7092ca61e4fcfeef9ca/examples/ …
> Translate `dir` attribute

- src/popper/commands/cmd_translate.py
- src/popper/translators/translator.py
- src/popper/translators/translator_task.py
- src/test/test_translator_task.py
This PR adds `TaskTranslator`, the class that translates popper workflows to [Taskfile](https://taskfile.dev/). Because Task does not provide container support, the translator generates `docker run` commands if the workflow specifies a Docker container as a runtime.
This is an early version and not all features are implemented. See `Next Action` for details.
The `tasks` attribute in Taskfile is an object where its keys are task names. On the other hand, `steps` in Popper is an array and each step has an ID. 
When you run the `task` command without specifying the task name, it will attempt to run the task named `default`. Because we expect Task to run the commands in order, the translator automatically generates `default` task that calls other tasks in order.
For example, the translation …
> [Translator] Create TaskTranslator

- src/popper/translators/translator_task.py
- src/test/test_translator_task.py
This PR adds support for `env` options in Popper-to-Task translator.
It adds the following two functionalities to the translator.
- make environment variables defined in the Popper workflow available
- make the pre-defined variables (e.g. `GIT_COMMIT`) available
Popper provides two ways to define environment variables.
The first is to use the `options.env` attribute. The environment variables defined in this attribute would be available from all steps in the workflow.
The second is to use the `steps[i].env` attribute. The variables defined in this attribute are only available in the step.
When the Popper parser parses a workflow, it automatically reads variables defined in `options.env` and merges them into `steps[i].env`. 
Therefore, the Popper-to-Task translator reads that merged …
> translator: support `env` options in Popper-to-Task translator

- docs/sections/cli_features.md
- src/popper/translators/translator_task.py
- src/test/test_translator_task.py
This PR adds documentation for Popper-to-Task translator. 
It also makes changes to Popper-to-Task translator to raise an error if the source popper workflow contains a step whose id is `default`, which conflicts with the Task's reserved name.
> Document Popper-to-Task Translator
